fix an error ci reported
When I reabase this change[1] to master, CI reported an error:
writefrudata.cpp: In function ‘int ipmiPopulateFruAreas(uint8_t*, size_t,
FruAreaVector&)’:
writefrudata.cpp:527:43: error: value computed is not used
[-Werror=unused-value]
  527 |             uint8_t areaData[areaLen] = {0};
      |                                           ^
writefrudata.cpp: In function ‘int validateFRUArea(uint8_t, const char*,
sdbusplus::bus_t&, bool)’:
writefrudata.cpp:671:34: error: value computed is not used
[-Werror=unused-value]
  671 |     uint8_t fruData[dataLen] = {0};

It was passed on gcc11, and we updated gcc to 12 [2]

I don't know why gcc reports an 'unused-value' warning, but
variable-length arrays are not standard c++[3]. So I just changed them to
std::vector

[1] https://gerrit.openbmc.org/c/openbmc/ipmi-fru-parser/+/47421, PS2
[2] https://gerrit.openbmc.org/c/openbmc/openbmc-build-scripts/+/57020
[3] https://stackoverflow.com/questions/1887097/why-arent-variable-length-arrays-part-of-the-c-standard

Signed-off-by: John Wang <wangzhiqiang02@inspur.com>
Change-Id: Ifc605a85d3dc9ad10b993a292fb2cf848b7b42f3